name: firereport
description: "Project for managing defect reports and checklists"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2024.11.09+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.6.0
  image_picker: ^1.1.2
  flutter_riverpod: ^2.5.3
  feedback: ^3.1.0
  package_info_plus: ^8.1.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true